Repository 202306-NEA-DZ-FEW/team-five, pull requests merged in 2023-11, with the labels that each got.

#131 feat: remove the repeated 2023 from the footer translation
  public/locales/ar/footer.json
  public/locales/en/footer.json
Labels: Style

#171 feat(new page): create 404 page
  public/locales/ar/error.json
  public/locales/en/error.json
  public/notfound.png
  src/components/FeedbackForm/index.jsx
  src/pages/error/index.jsx
Labels: documentation, Style

#174 feat(feedback form): create feedback form
  package-lock.json
  package.json
  public/locales/ar/error.json
  public/locales/en/error.json
  src/components/FeedbackForm/index.jsx
  src/pages/404.jsx
  src/pages/error/index.jsx
Labels: documentation, enhancement, service, UI/UX

#190 fix(404 page): add translation to feedback form
  public/locales/ar/error.json
  public/locales/en/error.json
  src/components/FeedbackForm/index.jsx
Labels: bug, documentation

#192 test(404 page): snapshot test feedback form
  src/components/FeedbackForm/__test__/FeedbackForm.test.js
  src/components/FeedbackForm/__test__/__snapshots__/FeedbackForm.test.js.snap
Labels: Test
